version: "3.7"
services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami/redis/data'
  dealer:
    image: dealer
    ports:
      - 8080:8080
    volumes:
      - ./docker/development.yml:/etc/app/application.yml
    networks:
      - app_net
volumes:
  redis_data:
    driver: local
networks:
 app_net:
   driver: bridge
